### ISSUE TITLE
AboutPage 모바일 버전 margin 변경 요청

### ISSUE THREAD

**Issue by sky-innerpeace** [DS-WISCOM/front-end#25]
![image](https://user-images.githubusercontent.com/57867252/199509102-1e17f432-4cd0-4c35-b10b-c54eeaa4c59e.png)
PC버전 크기로 적용했던 마진 값 때문에 모바일 버전에서 어색하게 보이는 것 같습니다. @media 적용해서 화면 크기 별로 마진값이 다르게 적용될 수 있도록 해주세요!
![image](https://user-images.githubusercontent.com/57867252/199509380-00aa1e8b-4b25-47b8-bb9b-d7b4be53ba42.png)

**Comment by yellow-jam** [comment]
제가 PC버전에서 마진값을 저렇게 설정한 이유가 생각나지 않아(...) 통일했습니다!
